{
 "title": "PostgreSQL Service Health",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(pg_cluster)" } },
   {
    "name": "role",
    "query": {
     "query": "label_values({pg_cluster=\"[[cluster]]\", exp_type!=\"pgbouncer\"},role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Saturation (pct used)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}) without (pod,instance,ip) * 100 / sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}) without (pod,instance,ip)",
     "legendFormat": "Connections %"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m])) + sum(irate(pg_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))",
     "legendFormat": "Transactions"
    },
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",role=\"[[role]]\",state=\"active\"}) without (pod,instance,ip,datname)",
     "legendFormat": "Active connections"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_deadlocks{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m]))  without(pod,instance,ip,datname)",
     "legendFormat": "Deadlock "
    },
    {
     "expr": "sum(irate(pg_stat_database_conflicts{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}[1m])) without(pod,instance,ip,datname)",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "max(pg_exporter_last_scrape_error{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"}) without(pod,instance,ip,datname)",
     "legendFormat": "scrape error"
    },
    {
     "expr": "max(clamp_max(pg_stat_archiver_last_archive_age{pg_cluster=\"[[cluster]]\",role=\"[[role]]\"},1)) without (instance,pod,ip)",
     "legendFormat": "archive error"
    }
   ]
  }
 ]
}