apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: mixeway-flow
spec:
  postgresVersion: 18
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  users:
    - name: mixeway-flow
      databases:
        - mixeway-flow
      options: 'SUPERUSER'
  service:
    metadata:
      annotations:
        my-annotation: mixeway-flow
      labels:
        my-label: mixeway-flow
    type: LoadBalancer
    # nodePort: 31002
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi9-0.18.1-2550
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host all ccp_monitoring 127.0.0.0/8 scram-sha-256
          - host all ccp_monitoring ::1/128 scram-sha-256
          - host all ccp_monitoring all reject
          - local all all peer
          - host all all 0.0.0.0/0 md5
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  proxy:
    pgBouncer: {}
