apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: cn-lms-dev
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:ubi8-16.2-3.4-0
  postgresVersion: 16
  postGISVersion: "3.4"
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  users:
    - name: cn-lms-dev
      databases:
        - cn-lms-dev
      options: 'SUPERUSER'
  service:
    metadata:
      annotations:
        my-annotation: value1
      labels:
        my-label: value2
    type: LoadBalancer
    nodePort: 32001
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          pg_hba:
            - "hostnossl all all all md5"
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.5.1-0
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      repos:
      - name: repo1
        schedules:
            full: "0 1 * * 0"
            differential: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.21-3
